train_data_dir: "/home/ubuntu/crnn-lid/data/youtube/segmented/training.csv"
validation_data_dir: "/home/ubuntu/crnn-lid/data/youtube/segmented/validation.csv"
test_data_dir: "/home/ubuntu/crnn-lid/data/youtube/segmented/testing.csv"

batch_size: 128
learning_rate: 0.001
num_epochs: 50

data_loader: "Spectrogram2Loader"
color_mode: "L"  # L = bw or RGB
input_shape: [129, 500, 1]

model: "inceptionv3_crnn"

segment_length: 10  # number of seconds each spectogram represents
pixel_per_second: 50

# label_names: ["EN", "DE", "FR", "ES"]
# num_classes: 4

label_names: ["EN", "DE", "FR", "ES", "CN", "RUS"]
num_classes: 6
